[book]
title = "Allegro"
authors = ["hxrts", "tac0turtle"]
language = "en"
src = "docs"

[build]
build-dir = "docs/book"

[output.html]
default-theme = "light"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
mathjax-support = true

[output.html.playground]
editable = false

[preprocessor.mermaid]
